### PR TITLE
Add pin to Crust

### PR DESCRIPTION
**Pull request by badkk**
Since AAVE already deploy the frontend to IPFS(Pinata), we propose this PR to help AAVE's frontend extend more replicas.
Crust Network is an incentive protocol beyond IPFS, now it has 7000+ IPFS nodes and over 2000+ PB IPFS storage volume around the world. It can help AAVE's frontend unstoppable and make it more decentralized!

> SEEDS is Crust's account 12-word secret seeds, which can be applied [here](https://apps.crust.network/#/accounts), And DCF will totally support AAVE's storage cost on-chain.

### CODE REVIEW

**Comment by sakulstra** [comment]
hello @badkk & thx for your contribution <3

Where can i find the source of the library / it's missing in package.json & therefore not linked on npmjs.
Also is there a rest api instead? Seems like this package comes with quite some dependencies, for what essentially is an api call to a pinning service.

**Comment by badkk** [comment]
> hello @badkk & thx for your contribution <3
> 
> Where can i find the source of the library / it's missing in package.json & therefore not linked on npmjs. Also is there a rest api instead? Seems like this package comes with quite some dependencies, for what essentially is an api call to a pinning service.
> 
> Generally speaking, i'm in favor of utilizing multiple pinning services - i'm not sure though if this should happen from the main repository or community maintained mirrors. Could you please create an issue so that this can be a discussion.

Hey @sakulstra, thanks for the replying. Im sorry about lacking some context of this PR.

1. `Source code question`: crust-pin's source code is here(https://github.com/crustio/crust.js/tree/mainnet/packages/crust-pin), and the `README` shows the basic working process;
2. `Change to RESTful API call question`: Yes, Crust also has standard IPFS pinning service, and the introduction it's here(https://wiki.crust.network/docs/en/buildIPFSW3AuthPin), if you prefer this way, we can change the code into calling the web3-authed pinning service;

**Additional context**:
1. `crust-pin` node pacakge already been used as CD process by `Polkadot Apps`, here is the code ref(https://github.com/polkadot-js/apps/blob/master/scripts/ipfsUpload.mjs#L94-L99)
2. `The Github Action: ipfs-crust-action`  already been used by Uniswap, here is the code ref(https://github.com/Uniswap/interface/blob/main/.github/workflows/release.yaml#L58-L64)

**Comment by badkk** [comment]
> hello @badkk & thx for your contribution <3
> 
> Where can i find the source of the library / it's missing in package.json & therefore not linked on npmjs. Also is there a rest api instead? Seems like this package comes with quite some dependencies, for what essentially is an api call to a pinning service.
> 
> Generally speaking, i'm in favor of utilizing multiple pinning services - i'm not sure though if this should happen from the main repository or community maintained mirrors. Could you please create an issue so that this can be a discussion.

Hey @sakulstra, thanks for the replying. Im sorry about lacking some context of this PR.

1. `Source code question`: crust-pin's source code is here(https://github.com/crustio/crust.js/tree/mainnet/packages/crust-pin), and the `README` shows the basic working process;
2. `Change to RESTful API call question`: Yes, Crust also has standard IPFS pinning service, and the introduction it's here(https://wiki.crust.network/docs/en/buildIPFSW3AuthPin), if you prefer this way, we can change the code into calling the web3-authed pinning service;

**Additional context**:
1. `crust-pin` node pacakge already been used as CD process by `Polkadot Apps`, here is the code ref(https://github.com/polkadot-js/apps/blob/master/scripts/ipfsUpload.mjs#L94-L99)
2. `The Github Action: ipfs-crust-action`  already been used by Uniswap(same code with `crust-pin`, but in `Github Action` way), here is the code ref(https://github.com/Uniswap/interface/blob/main/.github/workflows/release.yaml#L58-L64), and here is the issue introduced why Uniswap need Crust(https://github.com/Uniswap/interface/issues/1339)

**Comment by LowEntropyBody** [comment]
Great idea!

**Comment by yyd106** [comment]
@badkk I have created issue #145 as @sakulstra 's suggestion. Let's move to the issue to have more discussion.

**Comment by sakulstra** [comment]
closing as superseded

**Pull request closed without merging**
