### PR TITLE
Updated info message in the AMPL market

### PR DESCRIPTION
**Pull request by aalavandhan**
Added a link to Ampleforth lending borrowing FAQ which describes AMPL lending borrowing behavior and commonly asked questions

Updated message:
> Ampleforth is an asset affected by rebasing. Visit the documentation or Ampleforth's FAQ to learn more.

### CODE REVIEW

**Comment by aalavandhan** [comment]
cc: @sakulstra

**Comment by sakulstra** [comment]
@aalavandhan thx for the contribution.
Seems like there are linting issues - if you can't manage to resolve them i'll have a look at the end of the week (wanted to check why lint-staged didn't pick them up).

**Comment by sakulstra** [comment]
hey, just double checked and seems like there are some issues with current setup.
Would be lovely if you could rebase on master once https://github.com/aave/aave-ui/pull/225 is merged and run `npm run lint:fix`

**Comment by sakulstra** [comment]
@aalavandhan  #225 is merged, please rebase and run lint:fix

**Comment by aalavandhan** [comment]
@sakulstra done! let me know if you need anything else

**Review by sakulstra — APPROVED** [review]

**Pull request merged**
